services:
  # ============================================
  # MICROSERVICES (Databases run locally)
  # ============================================

  api-gateway:
    build:
      context: ./api-gateway
      dockerfile: Dockerfile
    container_name: all-rounder-api-gateway
    ports:
      - "3000:3000"
    env_file:
      - ./api-gateway/.env
    depends_on:
      - user-service
      - content-service
    command: npm run start
    networks:
      - all-rounder-network
    restart: unless-stopped

  user-service:
    build:
      context: ./user-service
      dockerfile: Dockerfile
    container_name: all-rounder-user-service
    ports:
      - "3001:3001"
    env_file:
      - ./user-service/.env
    command: npm run start
    networks:
      - all-rounder-network
    restart: unless-stopped

  content-service:
    build:
      context: ./content-service
      dockerfile: Dockerfile
    container_name: all-rounder-content-service
    ports:
      - "3002:3002"
    env_file:
      - ./content-service/.env
    command: npm run start
    networks:
      - all-rounder-network
    restart: unless-stopped



networks:
  all-rounder-network:
    driver: bridge

volumes:
  postgres_data:
  mongo_data:
  redis_data:
  kafka_data:
